name: emccd-paper
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9.18
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - numpy=1.26.1
  - scipy=1.11.3
  - scikit-image=0.22.0
  - pyyaml=6.0.1
  - tifffile=2023.9.26
  - pip
  - pip:
      - einops==0.7.0
      - timm==0.9.7
      - lpips==0.1.4
      - pytest>=7.4
